Uploading Task 1
witalikh/pmi_25_khomyn_programming pull request #1
Opened 2021-09-10 07:08 UTC by witalikh

2021-09-16 13:49 UTC, tetianastoyko requested changes

2021-09-16 13:49 UTC, tetianastoyko commented on Task 1.py
> +
Програма не поділена на логічні частини - функції, що вимагалось і озвучувалось на парі
Для отримання унікальних значень не повинні були використовуватись вбудовані методи, тоді ваше завдання простіше, ніж у інших.

2021-09-16 14:30 UTC, witalikh commented on Task 1.py
> +
Перепрошую, момент з вбудованими методами я прослухав. Дякую за зауваження

2021-09-23 16:20 UTC, tetianastoyko approved these changes

2021-09-29 20:13 UTC, merged